name: flutter_qr_bar_scanner_example
description: Demonstrates how to use the flutter_qr_bar_scanner plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_qr_bar_scanner:
    path: ../

flutter:
  uses-material-design: true